apiVersion: 1

datasources:
  - name: CartoSky Tempo
    uid: cartosky-tempo
    type: tempo
    access: proxy
    url: http://127.0.0.1:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: cartosky-prometheus
